---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: berrycloud/maven-aws-cli-node    
    
inputs:
- name: concourse-example
- name: ~/.aws

run:
  path: concourse-example/ci/scripts/deploy_lambda.sh