---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: berrycloud/maven-aws-cli-node    

inputs:
- name: concourse-example

run:
  path: project-src/ci/scripts/run_test.sh