---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: berrycloud/maven-aws-cli-node    
    
inputs:
- name: concourse-example

outputs:
- name: aws-cred

run:
  path: concourse-example/ci/scripts/update_aws.sh