---
resource_types:
  - name: npm-cache
    type: docker-image
    source:
      repository: ymedlop/npm-cache-resource
      tag: latest

resources:
  - name: concourse-example
    type: git
    source: &repo-source
      uri: https://github.com/madhusudangohil/concourse-example.git
      branch: master
  - name: dependency-cache
    type: npm-cache
    source:
      <<: *repo-source
      paths:
        - package.json
jobs:
  - name: install-dependencies
    plan:
      - get: concourse-example
        trigger: true
      - get: dependency-cache
  - name: run-tests
    plan:
      - get: concourse-example
        trigger: true
        passed:
           - install-dependencies
      - get: dependency-cache
        passed: 
           - install-dependencies
      - task: run the test suite
        file: concourse-example/ci/tasks/run_tests.yml
  - name: set-aws
    plan:
      - get: concourse-example
        trigger: true
        passed: 
           - run-tests 
      - task: update credentials
        file: concourse-example/ci/tasks/update_aws.yml
  - name: deploy lambda
    plan:
    - get: concourse-example
      trigger: true
      passed:
        - set-aws      
    - task: run-aws-commands
      file: concourse-example/ci/tasks/deploy_lambda.yml