---
resources:
  - name: project-src
    type: git
    source:
      uri: https://github.com/madhusudangohil/concourse-example.git
      branch: master
jobs:
  - name: unit-tests
    plan:
    - get: project-src
      trigger: true
    - task: run-unit-tests
      file: project-src/ci/tasks/unit-tests.yml
      
  - name: deploy-lambda
    plan:
    - get: project-src
      passed: 
         - unit-tests 
      trigger: true
    - task: run-aws-commands
      file: project-src/ci/tasks/aws-commands.yml